// WeDelivery E2E: 6 Major UI Automation Scenarios (Playwright)
// All selectors are verified against web/src source code.
//
// Prerequisites: Frontend running via `npm run dev` (http://localhost:3000, do NOT enable VITE_MOCK=1); Backend on :8080
// Setup: npm i -D @playwright/test && npx playwright install chromium
// Run (from web/ directory): npx playwright test wedelivery.spec.js
// Screenshots saved to: e2e/screenshots/ (auto-created)
//
// Note: Case 5 depends on tracking code generated by Case 4 (stored in e2e/.tracking-code); run sequentially.

import { test, expect } from '@playwright/test';
import fs from 'node:fs';

test.use({ baseURL: 'http://localhost:3000' });
const shot = (n) => `e2e/screenshots/${n}.png`;

test.describe('WeDelivery E2E — 6 Core Scenarios', () => {
  test.describe.configure({ timeout: 120000 });

  async function login(page, username, password = 'password123') {
    await page.goto('/login');
    await page.locator('input[placeholder="Your username"]').fill(username);
    await page.locator('input[placeholder="Enter your password"]').fill(password);
    await page.locator('button', { hasText: 'Log in' }).click();
  }

  const addrInput = (page, i) =>
    page.locator('input[placeholder="Street address, e.g. 500 Howard St"]').nth(i);

  async function pickDemoAddress(page, index, keyword) {
    const input = addrInput(page, index);
    await input.click();
    await input.fill(keyword);
    const dd = page.locator('.ant-select-dropdown');
    await expect(dd).toBeVisible({ timeout: 15000 });
    await dd.locator('.ant-select-item-option', { hasText: '· demo' }).first().click();
    await expect(page.locator('text=verified ✓')).toHaveCount(index + 1, { timeout: 15000 });
  }

  async function fillValidAddresses(page) {
    await page.locator('button', { hasText: '+ Create a new delivery' }).click();
    await expect(page).toHaveURL(/\/order\/new/);
    await expect(page.locator('text=Step 1 of 4: Addresses')).toBeVisible();
    await pickDemoAddress(page, 0, 'Salesforce');
    await pickDemoAddress(page, 1, 'Ferry');
    await page.locator('button', { hasText: 'Continue →' }).click();
    await expect(page.locator('text=Step 2 of 4: Package')).toBeVisible({ timeout: 20000 });
  }

  async function fillPackage(page, description, weightKg) {
    await page.locator('input[placeholder="e.g. Textbooks"]').fill(description);
    await page.locator('input[placeholder="e.g. 2.5"]').fill(String(weightKg));
  }

  async function goToOptionStep(page) {
    await fillValidAddresses(page);
    await fillPackage(page, 'Test Box', 1.5);
    await page.locator('button', { hasText: 'Continue →' }).click();
    await expect(page.locator('text=Recommended delivery options')).toBeVisible({ timeout: 30000 });
  }

  async function selectFirstDrone(page) {
    const droneCard = page.locator('.ant-card', { has: page.locator('h4', { hasText: 'Drone' }) }).first();
    await expect(droneCard).toBeVisible({ timeout: 15000 });
    await droneCard.locator('button', { hasText: 'Select' }).click();
    await expect(droneCard.locator('button', { hasText: 'Selected ✓' })).toBeVisible();
    await page.locator('button', { hasText: 'Continue →' }).last().click();
    await expect(page.locator('text=Order Summary')).toBeVisible({ timeout: 15000 });
  }

  test('Case 1: Invalid password rejected / Successful login / Non-admin redirected away from admin console', async ({ page }) => {
    await page.goto('/login');
    await page.locator('input[placeholder="Your username"]').fill('normal_user');
    await page.locator('input[placeholder="Enter your password"]').fill('password888');
    await page.locator('button', { hasText: 'Log in' }).click();
    await expect(page.locator('.ant-alert-error')).toContainText('Invalid username or password', { timeout: 15000 });
    await expect(page).toHaveURL(/\/login/);
    await page.screenshot({ path: shot('01-login-error') });

    await page.locator('input[placeholder="Enter your password"]').fill('password123');
    await page.locator('button', { hasText: 'Log in' }).click();
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await expect(page.locator('h2').first()).toContainText('normal_user');

    await page.goto('/admin');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await expect(page.locator('text=Admin access required')).toHaveCount(0);
    await page.screenshot({ path: shot('01-admin-redirect') });
  });

  test('Case 2a: Demo address autocomplete suggestion + verified badge', async ({ page }) => {
    await login(page, 'normal_user');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await page.locator('button', { hasText: '+ Create a new delivery' }).click();
    await expect(page).toHaveURL(/\/order\/new/);
    const pickup = addrInput(page, 0);
    await pickup.click();
    await pickup.fill('Salesforce');
    const dd = page.locator('.ant-select-dropdown');
    await expect(dd).toBeVisible({ timeout: 15000 });
    await page.screenshot({ path: shot('02a-autocomplete') });
    await dd.locator('.ant-select-item-option', { hasText: '· demo' }).first().click();
    await expect(page.locator('text=verified ✓').first()).toBeVisible({ timeout: 15000 });
    await page.screenshot({ path: shot('02a-verified') });
  });

  test('Case 2b: Malformed / gibberish address input is rejected', async ({ page }) => {
    await login(page, 'normal_user');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await page.locator('button', { hasText: '+ Create a new delivery' }).click();
    await expect(page).toHaveURL(/\/order\/new/);
    await pickDemoAddress(page, 0, 'Salesforce');
    await addrInput(page, 1).click();
    await addrInput(page, 1).fill('123456789xyz');
    await page.locator('button', { hasText: 'Continue →' }).click();
    await expect(page.locator('text=Address could not be found or is outside San Francisco')).toBeVisible({ timeout: 25000 });
    await expect(page).toHaveURL(/\/order\/new/);
    await page.screenshot({ path: shot('02b-garbage-blocked') });
  });

  test('Case 2c: Out-of-boundary address (Los Angeles) rejected', async ({ page }) => {
    await login(page, 'normal_user');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await page.locator('button', { hasText: '+ Create a new delivery' }).click();
    await expect(page).toHaveURL(/\/order\/new/);
    await pickDemoAddress(page, 0, 'Salesforce');
    await addrInput(page, 1).click();
    await addrInput(page, 1).fill('Sunset Blvd, Los Angeles');
    await page.locator('button', { hasText: 'Continue →' }).click();
    await expect(page.locator('text=Address could not be found or is outside San Francisco')).toBeVisible({ timeout: 25000 });
    await page.screenshot({ path: shot('02c-la-blocked') });
  });

  test('Case 2d: Map click on land -> auto-fills address with verified badge', async ({ page }) => {
    await login(page, 'normal_user');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await page.locator('button', { hasText: '+ Create a new delivery' }).click();
    await expect(page).toHaveURL(/\/order\/new/);
    const map = page.locator('.leaflet-container');
    await expect(map).toBeVisible({ timeout: 20000 });
    const box = await map.boundingBox();
    await map.click({ position: { x: box.width * 0.5, y: box.height * 0.5 } });
    await expect(page.locator('text=verified ✓').first()).toBeVisible({ timeout: 25000 });
    await page.screenshot({ path: shot('02d-map-click-land') });
  });

  test('Case 2e: Map click on ocean -> shows error requesting land point', async ({ page }) => {
    await login(page, 'normal_user');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await page.locator('button', { hasText: '+ Create a new delivery' }).click();
    await expect(page).toHaveURL(/\/order\/new/);
    const map = page.locator('.leaflet-container');
    await expect(map).toBeVisible({ timeout: 20000 });
    const box = await map.boundingBox();
    await map.click({ position: { x: box.width * 0.05, y: box.height * 0.5 } });
    await expect(page.locator('text=/No street address found at that spot|outside our San Francisco service area/').first()).toBeVisible({ timeout: 25000 });
    await page.screenshot({ path: shot('02e-map-click-ocean') });
  });

  test('Case 3: 4.5kg package filters out drone / 1.5kg package includes drone option', async ({ page }) => {
    await login(page, 'normal_user');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await fillValidAddresses(page);
    await fillPackage(page, 'Test Box', 4.5);
    await expect(page.locator('text=Over 3 kg — only robots can carry this')).toBeVisible();
    await page.screenshot({ path: shot('03a-weight-warning') });
    await page.locator('button', { hasText: 'Continue →' }).click();
    await expect(page.locator('text=Recommended delivery options')).toBeVisible({ timeout: 30000 });
    await expect(page.locator('h4', { hasText: 'Robot' }).first()).toBeVisible({ timeout: 15000 });
    await expect(page.locator('h4', { hasText: 'Drone' })).toHaveCount(0);
    await page.screenshot({ path: shot('03b-no-drone') });
    await page.locator('button', { hasText: '← Back' }).click();
    await expect(page.locator('text=Step 2 of 4: Package')).toBeVisible();
    await page.locator('input[placeholder="e.g. 2.5"]').fill('1.5');
    await page.locator('button', { hasText: 'Continue →' }).click();
    await expect(page.locator('text=Recommended delivery options')).toBeVisible({ timeout: 30000 });
    await expect(page.locator('h4', { hasText: 'Drone' }).first()).toBeVisible({ timeout: 15000 });
    await page.screenshot({ path: shot('03c-has-drone'), fullPage: true });
  });

  test('Case 4: Luhn check rejects invalid card / 0000 card declined by backend / Valid card order succeeds', async ({ page }) => {
    await login(page, 'normal_user');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await goToOptionStep(page);
    await selectFirstDrone(page);
    const cardInput = page.locator('input[placeholder="4242 4242 4242 4242"]');
    const payBtn = page.locator('button', { hasText: 'Pay $' });
    await cardInput.fill('4000123456780000');
    await payBtn.click();
    await expect(page.locator('text=looks mistyped')).toBeVisible({ timeout: 10000 });
    await expect(page).toHaveURL(/\/order\/new/);
    await page.screenshot({ path: shot('04a-luhn-blocked') });
    await cardInput.fill('4104332181960000');
    await payBtn.click();
    await expect(page.locator('text=Your card was declined')).toBeVisible({ timeout: 20000 });
    await expect(page).toHaveURL(/\/order\/new/);
    await page.screenshot({ path: shot('04b-declined') });
    await cardInput.fill('4242424242424242');
    await payBtn.click();
    await expect(page).toHaveURL(/\/track\?code=/, { timeout: 30000 });
    const code = new URL(page.url()).searchParams.get('code');
    expect(code).toMatch(/^[A-Za-z0-9]{16}$/);
    fs.writeFileSync('e2e/.tracking-code', code);
    await page.screenshot({ path: shot('04c-paid'), fullPage: true });
  });

  test('Case 5: Public tracking without login — progress bar / Leaflet map / status timeline', async ({ browser }) => {
    const code = fs.readFileSync('e2e/.tracking-code', 'utf8').trim();
    expect(code).toMatch(/^[A-Za-z0-9]{16}$/);
    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await page.goto(`/track?code=${code}`);
    await expect(page.locator('text=Track your delivery')).toBeVisible({ timeout: 15000 });
    await expect(page.locator('.ant-progress').first()).toBeVisible({ timeout: 30000 });
    await expect(page.locator('.leaflet-container').first()).toBeVisible({ timeout: 30000 });
    await expect(page.locator('.ant-timeline').first()).toBeVisible({ timeout: 30000 });
    await page.screenshot({ path: shot('05-tracking'), fullPage: true });
    await ctx.close();
  });

  test('Case 6: Admin dashboard — vehicle fleet statistics + 3 service stations', async ({ page }) => {
    await login(page, 'admin');
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 15000 });
    await page.goto('/admin');
    await expect(page.locator('text=Admin console')).toBeVisible({ timeout: 20000 });
    await expect(page.locator('text=Total vehicles')).toBeVisible();
    await expect(page.locator('.ant-table').first()).toBeVisible();
    await expect(page.locator('td', { hasText: 'Downtown' }).first()).toBeVisible({ timeout: 15000 });
    await page.screenshot({ path: shot('06-admin'), fullPage: true });
  });
});
